name: Build, Test & Deploy
defaults:
  run:
    working-directory: frontend
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build-and-test:
    timeout-minutes: 60
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies with PNPM
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Build the frontend
      - name: Build the frontend
        run: pnpm run build  # Ensure you build your Astro app

      # Upload the build artifact (after the build is completed)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: frontend/dist

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Create artifact from Playwright report (fixed typo)
      - name: Create Playwright report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/tests/report/playwright-report/*

  deploy:
    name: "Deploy to Combell"
    needs: build-and-test  # Only deploy if the build-and-test job is successful
    runs-on: ubuntu-latest
    steps:

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: frontend/dist

      # Deploy to Combell using FTP (correct version and secrets)
      - name: Deploy to Combell using FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}  # Add your Combell FTP server as a secret
          username: ${{ secrets.FTP_USERNAME }}  # Add your Combell FTP username as a secret
          password: ${{ secrets.FTP_PASSWORD }}  # Add your Combell FTP password as a secret
          local-dir: frontend/dist/   # Path to the 'dist' folde
          server-dir: www/astro-build/
